# Generated by Django 2.1.4 on 2018-12-18 16:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'blacklisted e-mail address',
                'verbose_name_plural': 'blacklisted e-mail addresses',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.PositiveSmallIntegerField(choices=[(0, 'success'), (1, 'not sent (blacklisted)'), (2, 'failure')])),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('log_message', models.TextField()),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_address', models.CharField(max_length=200)),
                ('from_address', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('encoded_message', models.TextField()),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='QueuedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'high'), (3, 'normal'), (5, 'low')], default=3)),
                ('deferred', models.DateTimeField(blank=True, null=True)),
                ('retries', models.PositiveIntegerField(default=0)),
                ('date_queued', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_mailer.Message')),
            ],
            options={
                'ordering': ('priority', 'date_queued'),
            },
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='django_mailer.Message'),
        ),
    ]
